// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Octogami.LunchTracker.Api.Infrastructure.Data;

namespace Octogami.LunchTracker.Api.Migrations
{
    [DbContext(typeof(LunchTrackerContext))]
    [Migration("20190324224714_AddDateToLunch")]
    partial class AddDateToLunch
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("lt")
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Octogami.LunchTracker.Api.Infrastructure.Data.Entities.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("ExternalUserId")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("IdentityProviderId");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdateDate");

                    b.HasKey("AppUserId");

                    b.HasAlternateKey("AppUserId", "IdentityProviderId");

                    b.HasIndex("IdentityProviderId");

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("Octogami.LunchTracker.Api.Infrastructure.Data.Entities.IdentityProvider", b =>
                {
                    b.Property<int>("IdentityProviderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("IdentityProviderId");

                    b.HasAlternateKey("Name");

                    b.ToTable("IdentityProvider");

                    b.HasData(
                        new
                        {
                            IdentityProviderId = 1,
                            Name = "Google"
                        });
                });

            modelBuilder.Entity("Octogami.LunchTracker.Api.Infrastructure.Data.Entities.Lunch", b =>
                {
                    b.Property<int>("LunchId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserId");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(9,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("RestaurantId");

                    b.Property<int>("RevisitId");

                    b.HasKey("LunchId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("RevisitId");

                    b.ToTable("Lunch");
                });

            modelBuilder.Entity("Octogami.LunchTracker.Api.Infrastructure.Data.Entities.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Verified");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurant");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            Name = "McDonald's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 2,
                            Name = "Starbucks",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 3,
                            Name = "Subway",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 4,
                            Name = "Taco Bell",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 5,
                            Name = "Burger King",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 6,
                            Name = "Wendy's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 7,
                            Name = "Chick-fil-A",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 8,
                            Name = "Dunkin' Donuts",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 9,
                            Name = "Domino's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 10,
                            Name = "Pizza Hut",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 11,
                            Name = "Panera Bread",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 12,
                            Name = "KFC",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 13,
                            Name = "Chipotle Mexican Grill",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 14,
                            Name = "Sonic Drive-In",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 15,
                            Name = "Applebee's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 16,
                            Name = "Olive Garden",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 17,
                            Name = "Buffalo Wild Wings",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 18,
                            Name = "Little Caesars",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 19,
                            Name = "Dairy Queen",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 20,
                            Name = "Arby's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 21,
                            Name = "Chili's Grill and Bar",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 22,
                            Name = "Jack in the Box",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 23,
                            Name = "IHOP",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 24,
                            Name = "Panda Express",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 25,
                            Name = "Popeyes Louisiana Kitchen",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 26,
                            Name = "Papa John's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 27,
                            Name = "Denny's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 28,
                            Name = "Outback Steakhouse",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 29,
                            Name = "Texas Roadhouse",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 30,
                            Name = "Jimmy John's Gourmet Sandwiches",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 31,
                            Name = "Cracker Barrel Old Country Store",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 32,
                            Name = "Hardee's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 33,
                            Name = "Red Lobster",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 34,
                            Name = "Whataburger",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 35,
                            Name = "The Cheesecake Factory",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 36,
                            Name = "Zaxby's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 37,
                            Name = "Golden Corral",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 38,
                            Name = "LongHorn Steakhouse",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 39,
                            Name = "Red Robin Gourmet Burgers and Brews",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 40,
                            Name = "Carl's Jr.",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 41,
                            Name = "Five Guys Burgers and Fries",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 42,
                            Name = "Culver's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 43,
                            Name = "TGI Fridays",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 44,
                            Name = "Waffle House",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 45,
                            Name = "Bojangles' Famous Chicken 'N Biscuits",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 46,
                            Name = "Steak 'n Shake",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 47,
                            Name = "Wingstop",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 48,
                            Name = "BJ's Restaurant and Brewhouse",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 49,
                            Name = "Jersey Mike's Subs",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 50,
                            Name = "Raising Cane's Chicken Fingers",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 51,
                            Name = "Bob Evans",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 52,
                            Name = "In-N-Out Burger",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 53,
                            Name = "Krispy Kreme",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 54,
                            Name = "P.F. Chang's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 55,
                            Name = "Hooters",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 56,
                            Name = "El Pollo Loco",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 57,
                            Name = "Papa Murphy's Pizza",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 58,
                            Name = "Ruby Tuesday",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 59,
                            Name = "Qdoba Mexican Eats",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 60,
                            Name = "Del Taco",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 61,
                            Name = "Church's Chicken",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 62,
                            Name = "Tim Hortons",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 63,
                            Name = "Cheddar's Scratch Kitchen",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 64,
                            Name = "Moe's Southwest Grill",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 65,
                            Name = "Firehouse Subs",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 66,
                            Name = "California Pizza Kitchen",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 67,
                            Name = "Ruth's Chris Steak House",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 68,
                            Name = "Carrabba's Italian Grill",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 69,
                            Name = "McAlister's Deli",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 70,
                            Name = "Jason's Deli",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 71,
                            Name = "Perkins Restaurant and Bakery",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 72,
                            Name = "Bonefish Grill",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 73,
                            Name = "Dickey's Barbecue Pit",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 74,
                            Name = "Baskin-Robbins",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 75,
                            Name = "Logan's Roadhouse",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 76,
                            Name = "Boston Market",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 77,
                            Name = "Auntie Anne's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 78,
                            Name = "Captain D's Seafood Kitchen",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 79,
                            Name = "Checkers Drive-In Restaurants",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 80,
                            Name = "Marco's Pizza",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 81,
                            Name = "White Castle",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 82,
                            Name = "Einstein Bros. Bagels",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 83,
                            Name = "Yard House",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 84,
                            Name = "Noodles and Co.",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 85,
                            Name = "Jamba Juice",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 86,
                            Name = "Dave and Buster's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 87,
                            Name = "O'Charly's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 88,
                            Name = "Potbelly Sandwich Shop",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 89,
                            Name = "Long John Silver's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 90,
                            Name = "Mellow Mushroom",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 91,
                            Name = "Round Table Pizza",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 92,
                            Name = "Cicis",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 93,
                            Name = "The Capital Grille",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 94,
                            Name = "Freddy's Frozen Custard and Steakburgers",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 95,
                            Name = "Maggiano's Little Italy",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 96,
                            Name = "Hungry Howie's Pizza",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 97,
                            Name = "Chuck E. Cheese's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 98,
                            Name = "Miller's Ale House",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 99,
                            Name = "Famous Dave's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 100,
                            Name = "Krystal Co.",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 101,
                            Name = "Tropical Smoothie Cafe",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 102,
                            Name = "Charleys Philly Steaks",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 103,
                            Name = "Cold Stone Creamery",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 104,
                            Name = "Corner Bakery Cafe",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 105,
                            Name = "Jet's Pizza",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 106,
                            Name = "Village Inn",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 107,
                            Name = "Chuy's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 108,
                            Name = "Taco John's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 109,
                            Name = "Shake Shack",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 110,
                            Name = "Pollo Tropical",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 111,
                            Name = "Pei Wei Asian Diner",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 112,
                            Name = "The Habit Burger Grill",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 113,
                            Name = "On the Border Mexican Grill and Cantina",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 114,
                            Name = "Au Bon Pain",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 115,
                            Name = "Pappadeaux Seafood Kitchen",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 116,
                            Name = "Schlotzsky's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 117,
                            Name = "Portillo's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 118,
                            Name = "Benihana",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 119,
                            Name = "Braum's Ice Cream and Dairy Stores",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 120,
                            Name = "Smashburger",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 121,
                            Name = "Zoes Kitchen",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 122,
                            Name = "Twin Peaks",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 123,
                            Name = "Bar Louie",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 124,
                            Name = "Smoothie King",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 125,
                            Name = "First Watch",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 126,
                            Name = "Ninety Nine Restaurants",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 127,
                            Name = "Fleming's Prime Steakhouse and Wine Bar",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 128,
                            Name = "Texas de Brazil Churrascaria",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 129,
                            Name = "Taco Cabana",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 130,
                            Name = "Rally's Hamburgers",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 131,
                            Name = "Fogo de Chao",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 132,
                            Name = "Peet's Coffee and Tea",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 133,
                            Name = "Friendly's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 134,
                            Name = "Hard Rock Cafe",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 135,
                            Name = "Joe's Crab Shack",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 136,
                            Name = "Blaze Pizza",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 137,
                            Name = "MOD Pizza",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 138,
                            Name = "Wienerschnitzel",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 139,
                            Name = "Old Chicago Pizza and Taproom",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 140,
                            Name = "Caribou Coffee",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 141,
                            Name = "Huddle House",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 142,
                            Name = "Godfather's Pizza",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 143,
                            Name = "Black Bear Diner",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 144,
                            Name = "Morton's The Steakhouse",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 145,
                            Name = "Seasons 52",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 146,
                            Name = "Bill Miller Bar-B-Q",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 147,
                            Name = "Sizzler",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 148,
                            Name = "Saltgrass Steak House",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 149,
                            Name = "Cooper's Hawk Winery and Restaurants",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 150,
                            Name = "Brio Tuscan Grille",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 151,
                            Name = "Sbarro",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 152,
                            Name = "Dutch Bros. Coffee",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 153,
                            Name = "Souplantation and Sweet Tomatoes",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 154,
                            Name = "Pizza Ranch",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 155,
                            Name = "Fazoli's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 156,
                            Name = "AandW All-American Food",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 157,
                            Name = "Sonny's BBQ",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 158,
                            Name = "Romano's Macaroni Grill",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 159,
                            Name = "UNO Pizzeria and Grill",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 160,
                            Name = "Which Wich Superior Sandwiches",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 161,
                            Name = "Big Boy",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 162,
                            Name = "Newk's Eatery",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 163,
                            Name = "Rubio's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 164,
                            Name = "Bahama Breeze Island Grille",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 165,
                            Name = "Mastro's Restaurants",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 166,
                            Name = "Legal Sea Foods",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 167,
                            Name = "Luby's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 168,
                            Name = "Claim Jumper",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 169,
                            Name = "Fuddruckers",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 170,
                            Name = "Shoney's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 171,
                            Name = "Penn Station East Coast Subs",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 172,
                            Name = "Cafe Rio Mexican Grill",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 173,
                            Name = "McCormick and Schmick's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 174,
                            Name = "Old Country Buffet",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 175,
                            Name = "Mimi's Cafe",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 176,
                            Name = "Buca di Beppo",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 177,
                            Name = "Taco Bueno",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 178,
                            Name = "Johnny Rockets",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 179,
                            Name = "la Madeleine Country French Cafe",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 180,
                            Name = "Bubba Gump Shrimp Co. Restaurant and Market",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 181,
                            Name = "Le Pain Quotidien",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 182,
                            Name = "Beef 'O' Brady's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 183,
                            Name = "Uncle Julio's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 184,
                            Name = "Fuzzy's Taco Shop",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 185,
                            Name = "Menchie's Frozen Yogurt",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 186,
                            Name = "Houlihan's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 187,
                            Name = "Pret a Manger",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 188,
                            Name = "Torchy's Tacos",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 189,
                            Name = "Sarku Japan",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 190,
                            Name = "Bertucci's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 191,
                            Name = "The Melting Pot",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 192,
                            Name = "J. Alexander's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 193,
                            Name = "Smokey Bones Bar and Fire Grill",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 194,
                            Name = "Kona Grill",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 195,
                            Name = "Bruegger's Bagels",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 196,
                            Name = "Cinnabon",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 197,
                            Name = "Islands Fine Burgers and Drinks",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 198,
                            Name = "Del Frisco's Double Eagle Steak House",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 199,
                            Name = "Yogurtland",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 200,
                            Name = "Pappasito's Cantina",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 201,
                            Name = "Eat'n Park",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 202,
                            Name = "Donatos Pizza",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 203,
                            Name = "Golden Chick",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 204,
                            Name = "The Original Pancake House",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 205,
                            Name = "Firebirds Wood Fired Grill",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 206,
                            Name = "WaBa Grill",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 207,
                            Name = "Rainforest Cafe",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 208,
                            Name = "Farmer Boys",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 209,
                            Name = "Baja Fresh Mexican Grill",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 210,
                            Name = "LaRosa's Pizzeria",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 211,
                            Name = "Lucille's Smokehouse Bar-B-Que",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 212,
                            Name = "Shari's Cafe and Pies",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 213,
                            Name = "Jack's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 214,
                            Name = "BurgerFi",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 215,
                            Name = "Black Angus Steakhouse",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 216,
                            Name = "Hurricane Grill and Wings",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 217,
                            Name = "The Old Spaghetti Factory",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 218,
                            Name = "Anthony's Coal Fired Pizza",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 219,
                            Name = "Wetzel's Pretzels",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 220,
                            Name = "Tilted Kilt Pub and Eatery",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 221,
                            Name = "Bravo Cucina Italiana",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 222,
                            Name = "Roosters",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 223,
                            Name = "Togo's Sandwiches",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 224,
                            Name = "Mountain Mike's Pizza",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 225,
                            Name = "Grand Lux Cafe",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 226,
                            Name = "Roy Rogers Restaurants",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 227,
                            Name = "Cantina Laredo",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 228,
                            Name = "Freebirds World Burrito",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 229,
                            Name = "Tijuana Flats",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 230,
                            Name = "Duffy's Sports Grill",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 231,
                            Name = "Lazy Dog Restaurant and Bar",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 232,
                            Name = "Biggby Coffee",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 233,
                            Name = "PDQ",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 234,
                            Name = "Johnny Carino's",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 235,
                            Name = "Marie Callender's Restaurant and Bakery",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 236,
                            Name = "Pizza Pro",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 237,
                            Name = "Villa Fresh Italian Kitchen",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 238,
                            Name = "STK",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 239,
                            Name = "Great American Cookies",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 240,
                            Name = "Wayback Burgers",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 241,
                            Name = "Pollo Campero",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 242,
                            Name = "The Coffee Bean and Tea Leaf",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 243,
                            Name = "Main Event",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 244,
                            Name = "Papa Gino's Pizzeria",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 245,
                            Name = "Quaker Steak and Lube",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 246,
                            Name = "Gatti's Pizza",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 247,
                            Name = "Rita's Ice",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 248,
                            Name = "Ponderosa",
                            Verified = true
                        },
                        new
                        {
                            RestaurantId = 249,
                            Name = "Il Fornaio",
                            Verified = true
                        });
                });

            modelBuilder.Entity("Octogami.LunchTracker.Api.Infrastructure.Data.Entities.Revisit", b =>
                {
                    b.Property<int>("RevisitId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value");

                    b.HasKey("RevisitId");

                    b.ToTable("Revisit");

                    b.HasData(
                        new
                        {
                            RevisitId = 1,
                            Value = "Unsure"
                        },
                        new
                        {
                            RevisitId = 2,
                            Value = "Yes"
                        },
                        new
                        {
                            RevisitId = 3,
                            Value = "No"
                        });
                });

            modelBuilder.Entity("Octogami.LunchTracker.Api.Infrastructure.Data.Entities.AppUser", b =>
                {
                    b.HasOne("Octogami.LunchTracker.Api.Infrastructure.Data.Entities.IdentityProvider", "IdentityProvider")
                        .WithMany()
                        .HasForeignKey("IdentityProviderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Octogami.LunchTracker.Api.Infrastructure.Data.Entities.Lunch", b =>
                {
                    b.HasOne("Octogami.LunchTracker.Api.Infrastructure.Data.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Octogami.LunchTracker.Api.Infrastructure.Data.Entities.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Octogami.LunchTracker.Api.Infrastructure.Data.Entities.Revisit", "Revisit")
                        .WithMany()
                        .HasForeignKey("RevisitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
