// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Octogami.LunchTracker.Api.Infrastructure.Data;

namespace Octogami.LunchTracker.Api.Migrations
{
    [DbContext(typeof(LunchTrackerContext))]
    partial class LunchTrackerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("lt")
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Octogami.LunchTracker.Api.Infrastructure.Data.Entities.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("ExternalUserId")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("IdentityProviderId");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdateDate");

                    b.HasKey("AppUserId");

                    b.HasAlternateKey("AppUserId", "IdentityProviderId");

                    b.HasIndex("IdentityProviderId");

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("Octogami.LunchTracker.Api.Infrastructure.Data.Entities.IdentityProvider", b =>
                {
                    b.Property<int>("IdentityProviderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("IdentityProviderId");

                    b.HasAlternateKey("Name");

                    b.ToTable("IdentityProvider");

                    b.HasData(
                        new
                        {
                            IdentityProviderId = 1,
                            Name = "Google"
                        });
                });

            modelBuilder.Entity("Octogami.LunchTracker.Api.Infrastructure.Data.Entities.AppUser", b =>
                {
                    b.HasOne("Octogami.LunchTracker.Api.Infrastructure.Data.Entities.IdentityProvider", "IdentityProvider")
                        .WithMany()
                        .HasForeignKey("IdentityProviderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
