set xact_abort on;
begin transaction;

create table Restaurant
(
  RestaurantId int identity(1,1) not null,
  RestaurantName varchar(60) not null,
  Verified bit not null default(0),
  CreatedAt datetime2 not null default(getutcdate()),

  constraint [PK_Restaurant] primary key clustered (RestaurantId asc),
  constraint [UX_Restaurant_RestaurantId] unique (RestaurantName)
);

insert into Restaurant
  (RestaurantName, Verified)
values
  ('McDonald''s', 1),
  ('Starbucks', 1),
  ('Subway', 1),
  ('Taco Bell', 1),
  ('Burger King', 1),
  ('Wendy''s', 1),
  ('Chick-fil-A', 1),
  ('Dunkin'' Donuts', 1),
  ('Domino''s', 1),
  ('Pizza Hut', 1),
  ('Panera Bread', 1),
  ('KFC', 1),
  ('Chipotle Mexican Grill', 1),
  ('Sonic Drive-In', 1),
  ('Applebee''s', 1),
  ('Olive Garden', 1),
  ('Buffalo Wild Wings', 1),
  ('Little Caesars', 1),
  ('Dairy Queen', 1),
  ('Arby''s', 1),
  ('Chili''s Grill and Bar', 1),
  ('Jack in the Box', 1),
  ('IHOP', 1),
  ('Panda Express', 1),
  ('Popeyes Louisiana Kitchen', 1),
  ('Papa John''s', 1),
  ('Denny''s', 1),
  ('Outback Steakhouse', 1),
  ('Texas Roadhouse', 1),
  ('Jimmy John''s Gourmet Sandwiches', 1),
  ('Cracker Barrel Old Country Store', 1),
  ('Hardee''s', 1),
  ('Red Lobster', 1),
  ('Whataburger', 1),
  ('The Cheesecake Factory', 1),
  ('Zaxby''s', 1),
  ('Golden Corral', 1),
  ('LongHorn Steakhouse', 1),
  ('Red Robin Gourmet Burgers and Brews', 1),
  ('Carl''s Jr.', 1),
  ('Five Guys Burgers and Fries', 1),
  ('Culver''s', 1),
  ('TGI Fridays', 1),
  ('Waffle House', 1),
  ('Bojangles'' Famous Chicken ''N Biscuits', 1),
  ('Steak ''n Shake', 1),
  ('Wingstop', 1),
  ('BJ''s Restaurant and Brewhouse', 1),
  ('Jersey Mike''s Subs', 1),
  ('Raising Cane''s Chicken Fingers', 1),
  ('Bob Evans', 1),
  ('In-N-Out Burger', 1),
  ('Krispy Kreme', 1),
  ('P.F. Chang''s', 1),
  ('Hooters', 1),
  ('El Pollo Loco', 1),
  ('Papa Murphy''s Pizza', 1),
  ('Ruby Tuesday', 1),
  ('Qdoba Mexican Eats', 1),
  ('Del Taco', 1),
  ('Church''s Chicken', 1),
  ('Tim Hortons', 1),
  ('Cheddar''s Scratch Kitchen', 1),
  ('Moe''s Southwest Grill', 1),
  ('Firehouse Subs', 1),
  ('California Pizza Kitchen', 1),
  ('Ruth''s Chris Steak House', 1),
  ('Carrabba''s Italian Grill', 1),
  ('McAlister''s Deli', 1),
  ('Jason''s Deli', 1),
  ('Perkins Restaurant and Bakery', 1),
  ('Bonefish Grill', 1),
  ('Dickey''s Barbecue Pit', 1),
  ('Baskin-Robbins', 1),
  ('Logan''s Roadhouse', 1),
  ('Boston Market', 1),
  ('Auntie Anne''s', 1),
  ('Captain D''s Seafood Kitchen', 1),
  ('Checkers Drive-In Restaurants', 1),
  ('Marco''s Pizza', 1),
  ('White Castle', 1),
  ('Einstein Bros. Bagels', 1),
  ('Yard House', 1),
  ('Noodles and Co.', 1),
  ('Jamba Juice', 1),
  ('Dave and Buster''s', 1),
  ('O''Charly''s', 1),
  ('Potbelly Sandwich Shop', 1),
  ('Long John Silver''s', 1),
  ('Mellow Mushroom', 1),
  ('Round Table Pizza', 1),
  ('Cicis', 1),
  ('The Capital Grille', 1),
  ('Freddy''s Frozen Custard and Steakburgers', 1),
  ('Maggiano''s Little Italy', 1),
  ('Hungry Howie''s Pizza', 1),
  ('Chuck E. Cheese''s', 1),
  ('Miller''s Ale House', 1),
  ('Famous Dave''s', 1),
  ('Krystal Co.', 1),
  ('Tropical Smoothie Cafe', 1),
  ('Charleys Philly Steaks', 1),
  ('Cold Stone Creamery', 1),
  ('Corner Bakery Cafe', 1),
  ('Jet''s Pizza', 1),
  ('Village Inn', 1),
  ('Chuy''s', 1),
  ('Taco John''s', 1),
  ('Shake Shack', 1),
  ('Pollo Tropical', 1),
  ('Pei Wei Asian Diner', 1),
  ('The Habit Burger Grill', 1),
  ('On the Border Mexican Grill and Cantina', 1),
  ('Au Bon Pain', 1),
  ('Pappadeaux Seafood Kitchen', 1),
  ('Schlotzsky''s', 1),
  ('Portillo''s', 1),
  ('Benihana', 1),
  ('Braum''s Ice Cream and Dairy Stores', 1),
  ('Smashburger', 1),
  ('Zoes Kitchen', 1),
  ('Twin Peaks', 1),
  ('Bar Louie', 1),
  ('Smoothie King', 1),
  ('First Watch', 1),
  ('Ninety Nine Restaurants', 1),
  ('Fleming''s Prime Steakhouse and Wine Bar', 1),
  ('Texas de Brazil Churrascaria', 1),
  ('Taco Cabana', 1),
  ('Rally''s Hamburgers', 1),
  ('Fogo de Chao', 1),
  ('Peet''s Coffee and Tea', 1),
  ('Friendly''s', 1),
  ('Hard Rock Cafe', 1),
  ('Joe''s Crab Shack', 1),
  ('Blaze Pizza', 1),
  ('MOD Pizza', 1),
  ('Wienerschnitzel', 1),
  ('Old Chicago Pizza and Taproom', 1),
  ('Caribou Coffee', 1),
  ('Huddle House', 1),
  ('Godfather''s Pizza', 1),
  ('Black Bear Diner', 1),
  ('Morton''s The Steakhouse', 1),
  ('Seasons 52', 1),
  ('Bill Miller Bar-B-Q', 1),
  ('Sizzler', 1),
  ('Saltgrass Steak House', 1),
  ('Cooper''s Hawk Winery and Restaurants', 1),
  ('Brio Tuscan Grille', 1),
  ('Sbarro', 1),
  ('Dutch Bros. Coffee', 1),
  ('Souplantation and Sweet Tomatoes', 1),
  ('Pizza Ranch', 1),
  ('Fazoli''s', 1),
  ('AandW All-American Food', 1),
  ('Sonny''s BBQ', 1),
  ('Romano''s Macaroni Grill', 1),
  ('UNO Pizzeria and Grill', 1),
  ('Which Wich Superior Sandwiches', 1),
  ('Big Boy', 1),
  ('Newk''s Eatery', 1),
  ('Rubio''s', 1),
  ('Bahama Breeze Island Grille', 1),
  ('Mastro''s Restaurants', 1),
  ('Legal Sea Foods', 1),
  ('Luby''s', 1),
  ('Claim Jumper', 1),
  ('Fuddruckers', 1),
  ('Shoney''s', 1),
  ('Penn Station East Coast Subs', 1),
  ('Cafe Rio Mexican Grill', 1),
  ('McCormick and Schmick''s', 1),
  ('Old Country Buffet', 1),
  ('Mimi''s Cafe', 1),
  ('Buca di Beppo', 1),
  ('Taco Bueno', 1),
  ('Johnny Rockets', 1),
  ('la Madeleine Country French Cafe', 1),
  ('Bubba Gump Shrimp Co. Restaurant and Market', 1),
  ('Le Pain Quotidien', 1),
  ('Beef ''O'' Brady''s', 1),
  ('Uncle Julio''s', 1),
  ('Fuzzy''s Taco Shop', 1),
  ('Menchie''s Frozen Yogurt', 1),
  ('Houlihan''s', 1),
  ('Pret a Manger', 1),
  ('Torchy''s Tacos', 1),
  ('Sarku Japan', 1),
  ('Bertucci''s', 1),
  ('The Melting Pot', 1),
  ('J. Alexander''s', 1),
  ('Smokey Bones Bar and Fire Grill', 1),
  ('Kona Grill', 1),
  ('Bruegger''s Bagels', 1),
  ('Cinnabon', 1),
  ('Islands Fine Burgers and Drinks', 1),
  ('Del Frisco''s Double Eagle Steak House', 1),
  ('Yogurtland', 1),
  ('Pappasito''s Cantina', 1),
  ('Eat''n Park', 1),
  ('Donatos Pizza', 1),
  ('Golden Chick', 1),
  ('The Original Pancake House', 1),
  ('Firebirds Wood Fired Grill', 1),
  ('WaBa Grill', 1),
  ('Rainforest Cafe', 1),
  ('Farmer Boys', 1),
  ('Baja Fresh Mexican Grill', 1),
  ('LaRosa''s Pizzeria', 1),
  ('Lucille''s Smokehouse Bar-B-Que', 1),
  ('Shari''s Cafe and Pies', 1),
  ('Jack''s', 1),
  ('BurgerFi', 1),
  ('Black Angus Steakhouse', 1),
  ('Hurricane Grill and Wings', 1),
  ('The Old Spaghetti Factory', 1),
  ('Anthony''s Coal Fired Pizza', 1),
  ('Wetzel''s Pretzels', 1),
  ('Tilted Kilt Pub and Eatery', 1),
  ('Bravo Cucina Italiana', 1),
  ('Roosters', 1),
  ('Togo''s Sandwiches', 1),
  ('Mountain Mike''s Pizza', 1),
  ('Grand Lux Cafe', 1),
  ('Roy Rogers Restaurants', 1),
  ('Cantina Laredo', 1),
  ('Freebirds World Burrito', 1),
  ('Tijuana Flats', 1),
  ('Duffy''s Sports Grill', 1),
  ('Lazy Dog Restaurant and Bar', 1),
  ('Biggby Coffee', 1),
  ('PDQ', 1),
  ('Johnny Carino''s', 1),
  ('Marie Callender''s Restaurant and Bakery', 1),
  ('Pizza Pro', 1),
  ('Villa Fresh Italian Kitchen', 1),
  ('STK', 1),
  ('Great American Cookies', 1),
  ('Wayback Burgers', 1),
  ('Pollo Campero', 1),
  ('The Coffee Bean and Tea Leaf', 1),
  ('Main Event', 1),
  ('Papa Gino''s Pizzeria', 1),
  ('Quaker Steak and Lube', 1),
  ('Gatti''s Pizza', 1),
  ('Rita''s Ice', 1),
  ('Ponderosa', 1),
  ('Il Fornaio', 1);

commit transaction;
set xact_abort off;
